import { test, expect } from "@playwright/test";
import logindata from "../utility/loginData.json";
import Login from "../pageObjectModel/login.page";
import EndToEnd1 from "../pageObjectModel/e2e1.page";
import vacencyData from "../utility/vacencyData.json";
test("end to end", async ({ page }) => {
  await page.goto(logindata.url);
  let login = new Login(page);
  await login.loginFunction(logindata);
  let endtoend = new EndToEnd1(page);
  await endtoend.recrutmentBtn.click();
  await endtoend.vacancyTab.click();
  await endtoend.addBtn.click();
  await endtoend.vacancyNameInp.first().fill(vacencyData.name);
  await endtoend.jobTitleSel.click();
  await page.keyboard.press("ArrowDown");
  await page.keyboard.press("Enter");
  await endtoend.discription.fill(vacencyData.discription);
  await endtoend.hiringManagetSel.fill(vacencyData.hiringManager);
  await page.keyboard.press("ArrowDown");
  await page.keyboard.press("Enter");
  await endtoend.numPosInp.fill("10");
  await endtoend.saveBtn.click();
  await page.goBack();
  await page.goBack();
  await page.waitForTimeout(1000);
  await page.screenshot({ path: "./screenshots/ene1.png" });
});
